name: Verificação de Segurança

on: [push]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Instalação do OWASP ZAP
      run: |
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz
        tar -xf ZAP_2.11.0_Linux.tar.gz
        export PATH=$PATH:$PWD/ZAP_2.11.0

    - name: Iniciar OWASP ZAP
      run: zap.sh -daemon -host 0.0.0.0 -port 8080

    - name: Executar Verificação de Segurança
      run: zap-cli quick-scan --self-contained --start-options "-config api.disablekey=true" --baseline "https://seu-site-aqui" -l High

    - name: Gerar Relatório de Segurança
      run: zap-cli report -o /github/workspace/security-report.html -f html

    - name: Publicar Relatório de Segurança
      uses: actions/upload-artifact@v2
      with:
        name: security-report
        path: /github/workspace/security-report.html
