image:
  name: alpine:latest
stages:
  - compile
  - audit
  - test
  - package
  - deploy

compile:
  stage: compile
  script:
    - sh ci/compile.sh codigo.txt

# scan virus:
#   stage: auditoria
#   script:
#     - sh ci/virus_scanner.sh

# scan vulnerabilities:
#   stage: auditoria
#   script:
#     - sh ci/vulnerabilities_scanner.sh

test:
  stage: teste
  script: - sh  ci/test.sh

package:
  before_script:
    - sh ci/install-dependedncies.sh
  stage: package
  atifacts:
    untracked: true
    expire_in: 10 minutes
  script:
    - sh ci/package.sh codigo.txt

deploy:
  stage: deploy
  dependencies:
    - package
  script:
    - sh ci/deploy.sh artifact.zip
